from parsers.door007 import parser_007
from parsers.asd import parser_asd
from parsers.bunker_doors import parser_bunker_doors
from parsers.command_doors import parser_command_doors
from parsers.fabric_doors import parser_fabric_doors
from parsers.forpost import parser_forpost
from parsers.intercon import parser_intercon
from parsers.labirint_doors import parser_labirint_doors
from parsers.mxd import parser_mxd
from parsers.ratibor import parser_ratibor
from parsers.str import parser_str
from parsers.sudar import parser_sudar
from parsers.termo_door import parser_termo_door